"""empty message

Revision ID: 62af2f0ac0fc
Revises: 9a8483d12c24
Create Date: 2021-04-08 00:31:01.395854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62af2f0ac0fc'
down_revision = '9a8483d12c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mortems', sa.Column('mortem_tags', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mortems', 'mortem_tags')
    # ### end Alembic commands ###
