"""empty message

Revision ID: 9a8483d12c24
Revises: 3f8a1776124b
Create Date: 2021-04-01 23:38:42.958194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8483d12c24'
down_revision = '3f8a1776124b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mortems', sa.Column('mortem_resolution', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mortems', 'mortem_resolution')
    # ### end Alembic commands ###
