"""empty message

Revision ID: c3c6b5516522
Revises: 8f84ca11e829
Create Date: 2021-04-09 00:24:53.755350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c6b5516522'
down_revision = '8f84ca11e829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('user_email', sa.String(length=20), nullable=False),
    sa.Column('user_password', sa.String(length=100), nullable=False),
    sa.Column('user_image', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('mortems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mortem_name', sa.String(length=100), nullable=False),
    sa.Column('mortem_impact', sa.String(length=20), nullable=False),
    sa.Column('mortem_url', sa.String(length=16), nullable=False),
    sa.Column('mortem_content', sa.Text(), nullable=False),
    sa.Column('mortem_resolution', sa.Text(), nullable=True),
    sa.Column('mortem_tags', sa.Text(), nullable=True),
    sa.Column('mortem_created', sa.DateTime(), nullable=False),
    sa.Column('mortem_updated', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('support_subject', sa.String(length=100), nullable=False),
    sa.Column('support_content', sa.Text(), nullable=False),
    sa.Column('support_created', sa.DateTime(), nullable=False),
    sa.Column('support_attach', sa.LargeBinary(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('support')
    op.drop_table('mortems')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
