"""empty message

Revision ID: f674c4c14cf9
Revises: 
Create Date: 2021-03-22 00:48:26.166225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f674c4c14cf9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doc')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=20), nullable=False),
    sa.Column('user_password', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_image', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('doc',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('doc_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('doc_content', sa.BLOB(), nullable=False),
    sa.Column('doc_crc', sa.VARCHAR(length=20), nullable=True),
    sa.Column('doc_created', sa.DATETIME(), nullable=False),
    sa.Column('doc_updated', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
