version: '3'

services:
  postgres:
    image: bitnami/postgresql:latest
    restart: always
    environment:
      - POSTGRES_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=docker
    volumes:
      - ./pgdata:/bitnami/postgresql
    ports:
      - 5432:5432
