# Default values for autopsy.

fullname: autopsy

replicaCount: 1

image:
  repository: ep4sh/autopsy
  pullPolicy: IfNotPresent
  tag: "latest"

autopsySecrets: autopsy-flask-dotenv

containerPort: 5000

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: app.ep4sh.cc
      paths: []
  tls: []

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}


# PostgreSQL settings
# Disabled until the issue won't be resolved https://github.com/bitnami/charts/issues/2061
database:
  enabled: false

postgresql:
  postgresqlUsername: "autopsy"
  postgresqlPassword: "autopsy"
  postgresqlDatabase: "autopsy"

