# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]


jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Good mortem!

      - name: Checkout
        uses: actions/checkout@v2

      - name: Find Tag
        id: tagger_old
        uses: jimschubert/query-tag-action@v1
        with:
          exclude: '*-rc*'
          commit-ish: 'HEAD~'
        # if you unshallow in a separate step, use the following option:
        # skip-unshallow: 'true'

      - name: Show Tag
        id: display
        run: |
            echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Get the latest tag from Git
        id: tagger
        run: git describe --abbrev=0 --long

      - name: Build and push
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            FLASK_APP: main.py
            FLASK_ENV: production
            FLASK_SECRET: ${{ secrets.FLASK_SECRET }}
          tags: |
            ep4sh/autopsy:latest
            ep4sh/autopsy:${{steps.tagger.outputs}}

      - name: Print image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


